<?php
	/*
		=============================
			THEME CUSTOM POST TYPE
		=============================
	*/

	/* Contact Custom Port Type */
	function yes_user_contact_custom_post_type() {
		$labels = array(
			'name'              => pll_('Messages'),
			'singular_name'     => pll_('Message'),
			'menu_name'         => pll_('Messages'),
			'name_admin_bar'    => pll_('Message'),
			'not_found'         => pll_('No Messages Found'),
		);
		$args = array(
			'labels'            => $labels,
			'show_ui'           => true,
			'show_in_menu'      => true,
			'capability_type'   => 'post',  // We Want to be as post not page
			'hierarchical'      => false,   // Because post can't be hierarchical so must put it false
			'menu_position'     => 26,
			'menu_icon'         => 'dashicons-email-alt',
			'supports'          => array( 'title', 'editor', 'author' )
		);
		// Register Our Post Type
		register_post_type( 'yes-user-contact', $args );
	}
	// hook for display our contact custom post in admin menu
	add_action( 'init', 'yes_user_contact_custom_post_type' );

	/*
	* function to create new columns and rename all columns as we want
	*/
	function yes_user_set_contact_columns( $columns ) {
		$newColumns = array();
		$newColumns['title']    = pll_('Full Name');
		$newColumns['message']  = pll_('Message');
		$newColumns['email']    = pll_('Email');
		$newColumns['date']     = pll_('Date');
		return $newColumns;
	}
	add_filter( 'manage_yes-user-contact_posts_columns', 'yes_user_set_contact_columns' );

	/*
	 * Function to print the value for every columns
	 */
	function yes_user_contact_custom_column( $column, $post_id ) {
		switch ( $column ) {
			case 'message' :
				// in the loop the $post_id is already set and get_the_excerpt will know witch type of message will print
				echo get_the_excerpt();
				break;
			case 'email':
				$email = get_post_meta( $post_id, '_contact_email_value_key', true );
				echo '<a href="mailto:' . $email . '">' . $email . '</a>';
				break;
		}
	}
	add_action( 'manage_yes-user-contact_posts_custom_column', 'yes_user_contact_custom_column', 10, 2 );

	/**** Create Contact Meta Box ****/
// Even If The Meta bax not related ot the custom post type but it related to the contact post type so we generate it in this file
	function yes_user_contact_add_meta_box() {
		add_meta_box( 'contact_email', pll_('User Email'), 'yes_user_contact_email_callback', 'yes-user-contact', 'side', 'default' );
	}
	// action to activate my function and generate the meta box
	add_action( 'add_meta_boxes', 'yes_user_contact_add_meta_box' );

// $post: will automatically pass by add_meta_box and it will care all information related to 'yes_user-contact' post type
	function yes_user_contact_email_callback( $post ) {
		wp_nonce_field( 'yes_user_save_contact_email_data', 'yes_user_contact_email_meta_box_nonce' );
		$value = get_post_meta( $post->ID, '_contact_email_value_key', true );
		// Print The input as wordpress theme build-in
		echo '<label for="yes_user_contact_email_field">' . pll_('User Email Address') . ': </label>';
		echo '<input type="email" id="yes_user_contact_email_field" name="yes_user_contact_email_field" value="' . esc_attr( $value ) . '" size="25" />';
	}

// function to print the email inside our meta box and save the post
	function yes_user_save_contact_email_data( $post_id ) {
		// check if the nonce is not set in the $_POST Method
		if ( ! isset( $_POST['yes_user_contact_email_meta_box_nonce'] ) ) {
			return;
		}
		// check if the nonce is valid and nonce is generated by wordpress and not generated by and hacker or another user
		if ( ! wp_verify_nonce( $_POST['yes_user_contact_email_meta_box_nonce'], 'yes_user_save_contact_email_data' ) ) {
			return;
		}
		// check is a manual save or automatically save | prevent the wordpress from saving by him self the meta box
		if ( defined('DOING_AUTOSAVE') && DOING_AUTOSAVE ) {
			return;
		}
		// Check for user permission
		if ( ! current_user_can( 'edit_post', $post_id ) ) {
			return;
		}
		// check if our input name yes_user_contact_email_field is in $_POST method
		if ( ! isset( $_POST['yes_user_contact_email_field'] ) ) {
			return;
		}
		// Retrieve the data
		$my_data = sanitize_text_field( $_POST['yes_user_contact_email_field'] );
		update_post_meta( $post_id, '_contact_email_value_key', $my_data );
	}
	// action to save the post in our contact custom post
	add_action( 'save_post', 'yes_user_save_contact_email_data' );
